TEX_FILES := $(wildcard *.tex)
PDF_FILES := $(TEX_FILES:.tex=.pdf)

all: $(PDF_FILES)
	$(MAKE) clean

# Rule to convert .tex to .pdf using pdflatex
%.pdf: %.tex
	pdflatex -interaction=nonstopmode $<

# Clean up auxiliary files generated by pdflatex
clean:
	rm -f *.aux *.log *.out *.toc *.nav *.snm

# Clean up all generated files including PDFs
distclean: clean
	rm -f $(PDF_FILES)

.PHONY: all clean distclean
